---
# tasks file for install_nginx


- name: Install nginx
  package: name=nginx state=present

- name: Install nginx  systemd script
  copy: src=nginx.service dest=/etc/systemd/system/nginx.service mode=0755

- name: Copy self signed key
  copy: src=nginx-selfsigned.key dest=/etc/ssl/private/nginx-selfsigned.key mode=0644
  
- name: Copy self signed certificate
  copy: src=nginx-selfsigned.crt dest=/etc/ssl/certs/nginx-selfsigned.crt mode=0644
  
- name: Copy nginx proxy config
  copy: src=proxy.conf dest=/etc/nginx/conf.d/proxy.conf mode=0644  
  
- name: Relead the config
  copy: src=proxy.conf dest=/etc/nginx/conf.d/proxy.conf mode=0644 

- name: Restart nginx service with daemon-reload to pick up systemd changes
  systemd: state=restarted daemon_reload=yes name=nginx.service
