---

- name: Install Java 1.8
  package: name=java-1.8.0-openjdk state=present

- name: Add group "tomcat"
  group: name=tomcat

- name: Add user "tomcat"
  user: name=tomcat group=tomcat home=/home/tomcat createhome=yes
  become: True
  become_method: sudo

- name: Create tomcat directory
  file: path=/opt/tomcat/apache-tomcat-8.5.35 owner=tomcat group=tomcat state=directory  mode=2774

- name: Download Tomcat
  get_url: url=http://apache.mirrors.ionfish.org/tomcat/tomcat-8/v8.5.35/bin/apache-tomcat-8.5.35.tar.gz dest=/opt/tomcat/apache-tomcat-8.5.35.tar.gz

- name: Extract Tomcat archive
  unarchive: src=/opt/tomcat/apache-tomcat-8.5.35.tar.gz dest=/opt/tomcat/ remote_src=yes

- name: Symlink install directory
  file: src=/opt/tomcat/apache-tomcat-8.5.35 path=/opt/tomcat-current owner=tomcat group=tomcat state=link mode=2774

- name: Change ownership of Tomcat installation
  file: path=/opt/tomcat/apache-tomcat-8.5.35 owner=tomcat group=tomcat state=directory recurse=yes

- name: Install Tomcat systemd script
  copy: src=tomcat.service dest=/etc/systemd/system/tomcat.service mode=0755

- name: Restart tomcat service with daemon-reload to pick up config changes
  systemd: state=restarted daemon_reload=yes name=tomcat.service enabled=yes
  when:
    - ansible_facts['distribution'] == "CentOS"
    - ansible_facts['distribution_major_version'] == "7"
