--- # This is the main playbook yaml for prod and staging environment.
- hosts: appservers
  remote_user: cloud_user
  become_user: root
  become_method: sudo
  become: yes 
  roles:
    - install_tomcat
    - deploy_app
    - install_nginx 
    - test_roles
  vars:
    - server_name: '13.52.99.197'
