---
# tasks file for install_nginx

- name: Install nginx
  package: name=nginx state=present

- name: Install nginx  systemd script
  copy: src=nginx.service dest=/etc/systemd/system/nginx.service mode=0755

- name: Create SSL private directory
  file: path=/etc/ssl/private/ owner=root group=root state=directory  mode=2774

- name: Copy self signed key
  copy: src=self-signed.key dest=/etc/ssl/private/self-signed.key mode=0644
  
- name: Copy self signed certificate
  copy: src=self-signed.crt dest=/etc/ssl/certs/self-signed.crt mode=0644

- name: Copy j2 file to server
  template: src=proxy.j2 dest=/etc/nginx/conf.d/proxy.conf mode=0644 

- name: Set SELinux config
  command: setsebool -P httpd_can_network_connect 1
  when: ansible_facts['os_family'] == "CentOS"

- name: Restart nginx service with daemon-reload to pick up systemd changes
  systemd: state=restarted daemon_reload=yes name=nginx.service enabled=yes
  when: 
    - ansible_facts['distribution'] == "CentOS"
    - ansible_facts['distribution_major_version'] == "7"
