---
# tasks file for test_role
#
- action: uri url=http://127.0.0.1:8080/devopschallenge/hello return_content=yes
  register: response

- fail:
    msg: 'application  is not running !!'
  when: "'Hello from Wirecard DevOps Challenge' not in response.content"

